# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/piplelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
   buildConfigration: 'Release'  

steps:
- script: dotnet build --configuration $(buildConfigration)
  displayName: 'dotnet build buildConfigration'